"""
Evaluate Persona Model on Held-out Synthetic Test Set
=====================================================

Loads the trained CatBoost artifact, runs it on the unseen test population
(generated by generate_test_data.py), and emits:

  outputs/reports/evaluation_report.md   — human-readable summary
  outputs/reports/per_class_metrics.csv  — precision/recall/F1 per persona
  outputs/reports/confusion_matrix.png   — heatmap
  outputs/reports/feature_importance.png — CatBoost gain importance
  outputs/reports/shap_summary.png       — SHAP beeswarm (top 25 features)

This script is *evaluation-only* — it never touches training data.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")           # headless
import matplotlib.pyplot as plt
from catboost import CatBoostClassifier
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, top_k_accuracy_score,
)

import pipeline_config as cfg
import feature_engineering as fe

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
log = logging.getLogger("eval")


# ============================================================================
# load
# ============================================================================

def load_model_and_metadata():
    if not cfg.MODEL_FILE.exists():
        raise FileNotFoundError(
            f"No trained model at {cfg.MODEL_FILE}. "
            f"Run train_catboost_persona_model.py first."
        )
    model = CatBoostClassifier()
    model.load_model(str(cfg.MODEL_FILE))
    classes = json.loads(cfg.LABEL_ENCODER_FILE.read_text())["classes"]
    feature_set = json.loads(cfg.LABEL_ENCODER_FILE.read_text()).get("feature_set", "telemetry")
    feature_cols = json.loads(cfg.FEATURE_LIST_FILE.read_text())
    return model, classes, feature_cols, feature_set


def load_test_features(feature_set: str) -> pd.DataFrame:
    log.info(f"reading raw test data from {cfg.TEST_RAW_DIR}")
    include_eps = feature_set == "with_episodes"
    feats = fe.features_from_directory(cfg.TEST_RAW_DIR, include_episode_features=include_eps)
    feats = fe.attach_persona_labels(feats, cfg.TEST_RAW_DIR / "users.csv")
    feats = feats.dropna(subset=["persona"])
    feats.to_csv(cfg.TEST_FEATURES_CSV, index=False)
    log.info(f"  test feature matrix: {feats.shape}")
    return feats


# ============================================================================
# metrics
# ============================================================================

def compute_metrics(model, df_test, classes, feature_cols):
    class_to_idx = {c: i for i, c in enumerate(classes)}
    y_true = df_test["persona"].map(class_to_idx).to_numpy()
    X = df_test[feature_cols].to_numpy(dtype=float)

    y_pred  = model.predict(X).flatten().astype(int)
    proba   = model.predict_proba(X)

    acc       = accuracy_score(y_true, y_pred)
    macro_f1  = f1_score(y_true, y_pred, average="macro")
    micro_f1  = f1_score(y_true, y_pred, average="micro")
    weighted_f1 = f1_score(y_true, y_pred, average="weighted")

    # Top-2 accuracy (only meaningful when more than 2 classes)
    top2 = top_k_accuracy_score(y_true, proba, k=2,
                                labels=list(range(len(classes))))

    log.info(f"TEST accuracy   = {acc:.4f}")
    log.info(f"TEST macro-F1   = {macro_f1:.4f}")
    log.info(f"TEST micro-F1   = {micro_f1:.4f}")
    log.info(f"TEST weighted-F1 = {weighted_f1:.4f}")
    log.info(f"TEST top-2 acc  = {top2:.4f}")

    rep = classification_report(
        y_true, y_pred, target_names=classes, digits=3,
        zero_division=0, output_dict=True,
    )

    per_class = pd.DataFrame({
        cl: {"precision": rep[cl]["precision"],
             "recall":    rep[cl]["recall"],
             "f1-score":  rep[cl]["f1-score"],
             "support":   rep[cl]["support"]}
        for cl in classes
    }).T
    per_class.to_csv(cfg.PER_CLASS_CSV)
    log.info(f"  saved per-class metrics -> {cfg.PER_CLASS_CSV}")

    cm = confusion_matrix(y_true, y_pred, labels=list(range(len(classes))))
    return {
        "accuracy": acc, "macro_f1": macro_f1, "micro_f1": micro_f1,
        "weighted_f1": weighted_f1, "top2_accuracy": top2,
    }, per_class, cm, y_true, y_pred, proba


def plot_confusion(cm, classes, out_path):
    fig, ax = plt.subplots(figsize=(10, 8))
    cm_norm = cm / np.maximum(1, cm.sum(axis=1, keepdims=True))
    im = ax.imshow(cm_norm, cmap="Blues", vmin=0, vmax=1)
    ax.set_xticks(range(len(classes))); ax.set_xticklabels(classes, rotation=45, ha="right")
    ax.set_yticks(range(len(classes))); ax.set_yticklabels(classes)
    ax.set_xlabel("Predicted"); ax.set_ylabel("True")
    ax.set_title("Confusion Matrix (row-normalized)")
    for i in range(len(classes)):
        for j in range(len(classes)):
            ax.text(j, i, f"{cm_norm[i,j]:.2f}",
                    ha="center", va="center",
                    color="white" if cm_norm[i,j] > 0.5 else "black",
                    fontsize=8)
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    plt.close()
    log.info(f"  saved confusion matrix -> {out_path}")


# ============================================================================
# interpretability
# ============================================================================

def plot_feature_importance(model, feature_cols, out_path, top_n=25):
    imp = model.get_feature_importance(type="FeatureImportance")
    df = (pd.DataFrame({"feature": feature_cols, "importance": imp})
            .sort_values("importance", ascending=True)
            .tail(top_n))
    fig, ax = plt.subplots(figsize=(8, 0.3 * len(df) + 1))
    ax.barh(df["feature"], df["importance"], color="#3a86ff")
    ax.set_xlabel("Importance (gain)")
    ax.set_title(f"CatBoost Feature Importance — top {top_n}")
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    plt.close()
    log.info(f"  saved feature importance -> {out_path}")
    return df.iloc[::-1].reset_index(drop=True)


def shap_summary(model, df_test, feature_cols, classes, out_path, max_users=300):
    """SHAP beeswarm of top features for the most populous predicted class."""
    try:
        import shap
    except ImportError:
        log.warning("shap not installed; skipping SHAP summary")
        return None

    sample = df_test.sample(n=min(max_users, len(df_test)),
                            random_state=cfg.RANDOM_SEED_TEST)
    X = sample[feature_cols].to_numpy(dtype=float)

    # CatBoost SHAP via TreeExplainer
    log.info("  computing SHAP values ...")
    t0 = time.time()
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X)   # shape: (samples, features, classes)
    log.info(f"    shap done in {time.time()-t0:.1f}s, shape={np.asarray(shap_values).shape}")

    # average absolute SHAP across classes -> per-feature importance
    sv = np.asarray(shap_values)
    if sv.ndim == 3:
        # multiclass
        mean_abs = np.mean(np.abs(sv), axis=(0, 2))
    else:
        mean_abs = np.mean(np.abs(sv), axis=0)

    order = np.argsort(mean_abs)[::-1][:25]
    df_top = pd.DataFrame({
        "feature": [feature_cols[i] for i in order],
        "mean_abs_shap": mean_abs[order],
    })

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.barh(df_top["feature"][::-1], df_top["mean_abs_shap"][::-1], color="#ff006e")
    ax.set_xlabel("Mean |SHAP value| (across classes)")
    ax.set_title("SHAP Feature Importance — top 25")
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    plt.close()
    log.info(f"  saved SHAP summary -> {out_path}")
    return df_top


# ============================================================================
# report
# ============================================================================

def write_report(metrics, per_class, top_features, top_shap, classes,
                 train_users_count, test_users_count, feature_set):
    md = []
    md.append("# Persona Classifier — Evaluation Report\n")
    md.append(f"**Feature set:** `{feature_set}`\n")
    md.append(f"**Training users:** {train_users_count}  ")
    md.append(f"**Test users:** {test_users_count}  ")
    md.append(f"**Classes:** {len(classes)}\n")

    md.append("## Headline Metrics (held-out test set)\n")
    md.append(f"- accuracy:     **{metrics['accuracy']:.4f}**")
    md.append(f"- top-2 acc:    **{metrics['top2_accuracy']:.4f}**")
    md.append(f"- macro-F1:     **{metrics['macro_f1']:.4f}**")
    md.append(f"- weighted-F1:  **{metrics['weighted_f1']:.4f}**")
    md.append(f"- micro-F1:     **{metrics['micro_f1']:.4f}**\n")

    md.append("## Per-Persona Metrics\n")
    md.append(per_class.round(3).to_markdown())
    md.append("")

    md.append("## Top Features (CatBoost gain)\n")
    md.append(top_features.head(15).round(3).to_markdown(index=False))
    md.append("")

    if top_shap is not None:
        md.append("## Top Features (SHAP, mean |value|)\n")
        md.append(top_shap.head(15).round(4).to_markdown(index=False))
        md.append("")

    md.append("## Artifacts\n")
    md.append(f"- model:                `{cfg.MODEL_FILE}`")
    md.append(f"- label encoder:        `{cfg.LABEL_ENCODER_FILE}`")
    md.append(f"- feature columns:      `{cfg.FEATURE_LIST_FILE}`")
    md.append(f"- confusion matrix:     `{cfg.CONFUSION_PNG}`")
    md.append(f"- feature importance:   `{cfg.FEATURE_IMP_PNG}`")
    md.append(f"- shap summary:         `{cfg.SHAP_SUMMARY_PNG}`")
    md.append(f"- per-class metrics:    `{cfg.PER_CLASS_CSV}`")

    cfg.EVAL_REPORT_MD.write_text("\n".join(md), encoding="utf-8")
    log.info(f"  saved markdown report -> {cfg.EVAL_REPORT_MD}")


# ============================================================================
# main
# ============================================================================

def main():
    cfg.banner("EVALUATE PERSONA MODEL")

    model, classes, feature_cols, feature_set = load_model_and_metadata()
    log.info(f"  model loaded.  classes={len(classes)}  features={len(feature_cols)}")
    log.info(f"  feature_set={feature_set}")

    df_test = load_test_features(feature_set)

    # filter test set to classes seen in training
    df_test = df_test[df_test["persona"].isin(classes)].reset_index(drop=True)

    metrics, per_class, cm, y_true, y_pred, proba = compute_metrics(
        model, df_test, classes, feature_cols)

    plot_confusion(cm, classes, cfg.CONFUSION_PNG)
    top_features = plot_feature_importance(model, feature_cols, cfg.FEATURE_IMP_PNG)
    top_shap = shap_summary(model, df_test, feature_cols, classes, cfg.SHAP_SUMMARY_PNG)

    train_users_count = len(pd.read_csv(cfg.TRAIN_RAW_DIR / "users.csv"))
    write_report(metrics, per_class, top_features, top_shap, classes,
                 train_users_count, len(df_test), feature_set)

    # also dump headline metrics as JSON for downstream tooling
    (cfg.REPORTS_DIR / "headline_metrics.json").write_text(json.dumps(metrics, indent=2))

    log.info("DONE.")


if __name__ == "__main__":
    main()
