-- Curated seed: İstanbul (28 etkinlik) + Ankara (14 etkinlik) = 42 etkinlik
-- starts_at değerleri now() + interval ile dinamik — seed her zaman geçerli kalır
-- is_recurring = true olan etkinliklerde starts_at/ends_at kasıtlı olarak null

insert into public.events
  (source, title, description, category, subcategory,
   venue_name, address, city, lat, lng,
   starts_at, ends_at, is_recurring, is_ticketed,
   price_min, price_max, currency, tags, popularity_score)
values

-- ═══════════════════════════════════════════════
--  İSTANBUL — MÜZİK
-- ═══════════════════════════════════════════════
('curated',
 'Caz Akşamı — Nardis Jazz Club',
 'Uluslararası caz sanatçılarının performansı. Her Perşembe akşamı.',
 'music', 'jazz',
 'Nardis Jazz Club', 'Kuledibi Sok. No:14, Beyoğlu', 'İstanbul',
 41.0282, 28.9740,
 now() + interval '3 days', now() + interval '3 days' + interval '3 hours',
 true, true, 250, 400, 'TRY',
 array['caz', 'canlı müzik', 'Beyoğlu'], 0.82),

('curated',
 'Rock Konseri — Küçükçiftlik Park',
 'Türk rock gruplarının açık hava konseri.',
 'music', 'rock',
 'Küçükçiftlik Park', 'Darülbedai Cad., Şişli', 'İstanbul',
 41.0617, 28.9994,
 now() + interval '8 days', now() + interval '8 days' + interval '4 hours',
 false, true, 350, 550, 'TRY',
 array['rock', 'açık hava', 'konser'], 0.76),

('curated',
 'Klasik Müzik Konseri — Lütfi Kırdar',
 'İstanbul Devlet Senfoni Orkestrası gala konseri.',
 'music', 'klasik',
 'Lütfi Kırdar Kongre Merkezi', 'Harbiye, Şişli', 'İstanbul',
 41.0495, 28.9945,
 now() + interval '5 days', now() + interval '5 days' + interval '2 hours 30 minutes',
 false, true, 150, 600, 'TRY',
 array['klasik müzik', 'senfoni', 'Harbiye'], 0.71),

('curated',
 'Babylon Canlı Performans',
 'Alternatif ve dünya müziği sanatçıları.',
 'music', 'alternatif',
 'Babylon', 'Şehbender Sok. No:3, Asmalımescit', 'İstanbul',
 41.0313, 28.9767,
 now() + interval '2 days', now() + interval '2 days' + interval '3 hours',
 true, true, 200, 350, 'TRY',
 array['canlı müzik', 'Beyoğlu', 'gece'], 0.79),

('curated',
 'Akustik Gece — Kadıköy Sahne',
 'Yeraltı ve bağımsız müzik sanatçıları akustik set.',
 'music', 'akustik',
 'Kadıköy Sahne', 'Moda Cad., Kadıköy', 'İstanbul',
 40.9853, 29.0234,
 now() + interval '4 days', now() + interval '4 days' + interval '3 hours',
 true, true, 100, 200, 'TRY',
 array['akustik', 'indie', 'Kadıköy'], 0.68),

-- ═══════════════════════════════════════════════
--  İSTANBUL — KÜLTÜR & SANAT
-- ═══════════════════════════════════════════════
('curated',
 'Pera Müzesi — Daimi Koleksiyon',
 'Anadolu Ağırlıkları ve Ölçüleri, Kütahya Çini ve Seramikleri, Oryantalist Resim koleksiyonları.',
 'culture', 'müze',
 'Pera Müzesi', 'Meşrutiyet Cad. No:65, Tepebaşı', 'İstanbul',
 41.0329, 28.9751,
 null, null,
 true, true, 75, 150, 'TRY',
 array['müze', 'sanat', 'Beyoğlu'], 0.88),

('curated',
 'İstanbul Modern — Çağdaş Sanat Sergisi',
 'Türk ve uluslararası çağdaş sanat eserleri. Galataport''ta yeni bina.',
 'culture', 'müze',
 'İstanbul Modern', 'Meclis-i Mebusan Cad., Karaköy', 'İstanbul',
 41.0236, 28.9813,
 null, null,
 true, true, 100, 200, 'TRY',
 array['çağdaş sanat', 'müze', 'Karaköy'], 0.91),

('curated',
 'SALT Galata — Mimarlık Sergisi',
 'Türk mimarlık tarihine dair kapsamlı arşiv ve sergi.',
 'culture', 'sergi',
 'SALT Galata', 'Bankalar Cad. No:11, Karaköy', 'İstanbul',
 41.0254, 28.9792,
 null, null,
 true, false, 0, 0, 'TRY',
 array['mimarlık', 'sergi', 'ücretsiz', 'Karaköy'], 0.74),

('curated',
 'Sakıp Sabancı Müzesi — Hat Sanatı Sergisi',
 'Osmanlı hat eserleri ve Sakıp Sabancı koleksiyonu.',
 'culture', 'müze',
 'Sakıp Sabancı Müzesi', 'Sakıp Sabancı Cad. No:42, Emirgan', 'İstanbul',
 41.0857, 29.0534,
 null, null,
 true, true, 100, 200, 'TRY',
 array['müze', 'hat sanatı', 'Emirgan', 'Boğaz'], 0.85),

('curated',
 'Kadıköy Tiyatro Festivali',
 'Bağımsız tiyatro gruplarının kısa oyunlar festivali.',
 'culture', 'tiyatro',
 'Kadıköy Kültür Merkezi', 'Söğütlüçeşme Cad., Kadıköy', 'İstanbul',
 40.9910, 29.0246,
 now() + interval '10 days', now() + interval '12 days',
 false, true, 50, 150, 'TRY',
 array['tiyatro', 'festival', 'Kadıköy'], 0.65),

-- ═══════════════════════════════════════════════
--  İSTANBUL — AÇIK HAVA & DOĞA
-- ═══════════════════════════════════════════════
('curated',
 'Maçka Parkı Sabah Yogası',
 'Her gün 07:30''da parkta açık hava yoga. Tüm seviyeler.',
 'outdoor', 'yoga',
 'Maçka Demokrasi Parkı', 'Maçka, Beşiktaş', 'İstanbul',
 41.0444, 29.0002,
 null, null,
 true, false, 0, 0, 'TRY',
 array['yoga', 'sabah', 'park', 'ücretsiz'], 0.72),

('curated',
 'Emirgan Korusu Doğa Yürüyüşü',
 'Boğaz manzaralı orman yolunda rehberli doğa yürüyüşü. Hafta sonları.',
 'outdoor', 'doğa yürüyüşü',
 'Emirgan Korusu', 'Emirgan, Sarıyer', 'İstanbul',
 41.0944, 29.0559,
 null, null,
 true, false, 0, 0, 'TRY',
 array['yürüyüş', 'doğa', 'Boğaz', 'ücretsiz'], 0.78),

('curated',
 'Belgrad Ormanı Bisiklet Turu',
 'Orman içi bisiklet rotaları. Kiralık bisiklet mevcut.',
 'outdoor', 'bisiklet',
 'Belgrad Ormanı Giriş', 'Bahçeköy, Sarıyer', 'İstanbul',
 41.1611, 28.9713,
 null, null,
 true, false, 0, 50, 'TRY',
 array['bisiklet', 'orman', 'doğa'], 0.81),

('curated',
 'Boğaz Gün Batımı Tekne Turu',
 'Boğaz köprüsü altından geçen 2 saatlik gün batımı turu.',
 'outdoor', 'tekne',
 'Beşiktaş İskelesi', 'Beşiktaş Meydanı', 'İstanbul',
 41.0439, 29.0056,
 now() + interval '1 days', now() + interval '1 days' + interval '2 hours',
 true, true, 200, 350, 'TRY',
 array['tekne', 'Boğaz', 'gün batımı'], 0.89),

('curated',
 'Adalar Bisiklet & Piknik',
 'Büyükada''da araç yok, bisiklet ile ada turu ve sahil pikniği.',
 'outdoor', 'bisiklet',
 'Büyükada Vapur İskelesi', 'Büyükada, Adalar', 'İstanbul',
 40.8738, 29.1199,
 null, null,
 true, false, 0, 80, 'TRY',
 array['ada', 'bisiklet', 'piknik', 'deniz'], 0.86),

-- ═══════════════════════════════════════════════
--  İSTANBUL — YEME-İÇME
-- ═══════════════════════════════════════════════
('curated',
 'Kadıköy Lezzet Turu',
 'Tarihi çarşıda rehber eşliğinde sokak lezzeti turu. 10 durak.',
 'food', 'yemek turu',
 'Kadıköy Çarşısı', 'Mühürdar Cad., Kadıköy', 'İstanbul',
 40.9905, 29.0256,
 null, null,
 true, true, 300, 300, 'TRY',
 array['lezzet', 'tur', 'Kadıköy', 'sokak yemeği'], 0.83),

('curated',
 'İstanbul Gurme Festivali',
 'Şehrin en iyi restoranları ve şefleri bir arada. 3 gün.',
 'food', 'festival',
 'Harbiye Cemil Topuzlu Parkı', 'Harbiye, Şişli', 'İstanbul',
 41.0479, 28.9905,
 now() + interval '14 days', now() + interval '16 days',
 false, false, 0, 0, 'TRY',
 array['festival', 'gurme', 'yemek', 'açık hava'], 0.77),

('curated',
 'Karaköy Kahve Festivali',
 'Türkiye''nin specialty kahve üreticileri ve baristalar.',
 'food', 'festival',
 'SALT Galata Avlusu', 'Bankalar Cad., Karaköy', 'İstanbul',
 41.0252, 28.9789,
 now() + interval '6 days', now() + interval '7 days',
 false, false, 0, 0, 'TRY',
 array['kahve', 'specialty', 'festival', 'Karaköy'], 0.74),

-- ═══════════════════════════════════════════════
--  İSTANBUL — SPOR
-- ═══════════════════════════════════════════════
('curated',
 'İstanbul Maratonu Hazırlık Koşusu',
 'Her pazar Fenerbahçe Parkı''nda 10km grup koşusu.',
 'sports', 'koşu',
 'Fenerbahçe Parkı', 'Bağdat Cad., Kadıköy', 'İstanbul',
 40.9716, 29.0400,
 null, null,
 true, false, 0, 0, 'TRY',
 array['koşu', 'maraton', 'grup', 'ücretsiz'], 0.69),

('curated',
 'Plaj Voleybolu — Florya',
 'Her hafta sonu plaj voleybolu. Katılım açık.',
 'sports', 'voleybol',
 'Florya Sahili', 'Florya, Bakırköy', 'İstanbul',
 40.9793, 28.7731,
 null, null,
 true, false, 0, 0, 'TRY',
 array['voleybol', 'plaj', 'spor', 'açık hava'], 0.64),

-- ═══════════════════════════════════════════════
--  İSTANBUL — ATÖLYE & EĞİTİM
-- ═══════════════════════════════════════════════
('curated',
 'Seramik Atölyesi — Cihangir',
 'Başlangıç seviyesi çömlek çekme ve boyama. 3 saatlik seans.',
 'workshop', 'seramik',
 'Cihangir Sanat Atölyesi', 'Akarsu Cad., Cihangir', 'İstanbul',
 41.0340, 28.9808,
 now() + interval '5 days', now() + interval '5 days' + interval '3 hours',
 true, true, 400, 600, 'TRY',
 array['seramik', 'atölye', 'el sanatları', 'Cihangir'], 0.71),

('curated',
 'Dijital Fotoğrafçılık Workshopu',
 'Kompozisyon ve ışık teknikleri. DSLR veya mirrorless gerekli.',
 'workshop', 'fotoğrafçılık',
 'Moda Sahil', 'Moda Cad., Kadıköy', 'İstanbul',
 40.9849, 29.0291,
 now() + interval '9 days', now() + interval '9 days' + interval '4 hours',
 false, true, 350, 500, 'TRY',
 array['fotoğrafçılık', 'workshop', 'sanat'], 0.67),

('curated',
 'Türk Mutfağı Pişirme Atölyesi',
 'Geleneksel Türk yemekleri yapım atölyesi. Malzemeler dahil.',
 'workshop', 'yemek',
 'Cooking Alaturka', 'Akbıyık Cad., Sultanahmet', 'İstanbul',
 41.0047, 28.9760,
 now() + interval '7 days', now() + interval '7 days' + interval '3 hours',
 true, true, 500, 700, 'TRY',
 array['yemek pişirme', 'Türk mutfağı', 'atölye'], 0.75),

-- ═══════════════════════════════════════════════
--  İSTANBUL — AİLE
-- ═══════════════════════════════════════════════
('curated',
 'Çocuk Tiyatrosu — Masal Diyarı',
 '4-10 yaş arası çocuklar için interaktif peri masalı oyunu.',
 'family', 'tiyatro',
 'Şişli Kültür Merkezi', 'Halaskargazi Cad., Şişli', 'İstanbul',
 41.0570, 28.9880,
 now() + interval '6 days', now() + interval '6 days' + interval '1 hours 30 minutes',
 true, true, 100, 180, 'TRY',
 array['çocuk', 'tiyatro', 'aile', 'masal'], 0.73),

('curated',
 'Bilim Merkezi Hafta Sonu Etkinliği',
 'İnteraktif bilim deneyleri ve atölyeler. 6-14 yaş.',
 'family', 'eğitim',
 'Koç Müzesi Bilim Merkezi', 'Hasköy Cad., Hasköy', 'İstanbul',
 41.0453, 28.9597,
 null, null,
 true, true, 80, 150, 'TRY',
 array['bilim', 'çocuk', 'eğitim', 'müze'], 0.80),

('curated',
 'Emirgan Parkı Piknik Günü',
 'Boğaz kenarında aile piknikleri için geniş çim alan ve çocuk oyun parkı.',
 'family', 'piknik',
 'Emirgan Parkı', 'Emirgan, Sarıyer', 'İstanbul',
 41.0918, 29.0549,
 null, null,
 true, false, 0, 0, 'TRY',
 array['piknik', 'park', 'aile', 'Boğaz', 'ücretsiz'], 0.84),

-- ═══════════════════════════════════════════════
--  İSTANBUL — KÜLTÜR (ek)
-- ═══════════════════════════════════════════════
('curated',
 'Topkapı Sarayı Rehberli Tur',
 'Osmanlı saray kompleksi, hazine ve harem bölümü dahil.',
 'culture', 'tarihi tur',
 'Topkapı Sarayı', 'Sultanahmet, Fatih', 'İstanbul',
 41.0115, 28.9833,
 null, null,
 true, true, 150, 400, 'TRY',
 array['tarihi', 'müze', 'Osmanlı', 'Sultanahmet'], 0.93),

('curated',
 'Street Art Turu — Karaköy & Tophane',
 'Karaköy''ün grafiti ve sokak sanatı eserlerini keşfet.',
 'culture', 'tur',
 'Karaköy Meydanı', 'Karaköy, Beyoğlu', 'İstanbul',
 41.0232, 28.9748,
 null, null,
 true, true, 150, 200, 'TRY',
 array['street art', 'tur', 'Karaköy', 'sanat'], 0.66),

-- ═══════════════════════════════════════════════
--  ANKARA — MÜZİK
-- ═══════════════════════════════════════════════
('curated',
 'Cumhurbaşkanlığı Senfoni Orkestrası Konseri',
 'CSO''nun aylık abonelik konseri. Uluslararası solistler.',
 'music', 'klasik',
 'CSO Ada Ankara', 'Çukurambar Mah., Çankaya', 'Ankara',
 39.9051, 32.8229,
 now() + interval '11 days', now() + interval '11 days' + interval '2 hours 30 minutes',
 true, true, 100, 500, 'TRY',
 array['senfoni', 'klasik müzik', 'CSO', 'Ankara'], 0.87),

('curated',
 'Ankara Caz Festivali',
 'Açık hava ve kapalı mekanlarda ulusal ve uluslararası caz sanatçıları.',
 'music', 'caz',
 'Kızılay Meydanı & Çeşitli Mekanlar', 'Çankaya, Ankara', 'Ankara',
 39.9199, 32.8543,
 now() + interval '20 days', now() + interval '23 days',
 false, false, 0, 200, 'TRY',
 array['caz', 'festival', 'Ankara', 'açık hava'], 0.79),

('curated',
 'Akustik Gece — Keyifli Mekan',
 'Kızılay''ın popüler bar sahnesinde haftalık akustik performans.',
 'music', 'akustik',
 'Keyifli Mekan', 'Konur Sok., Kızılay', 'Ankara',
 39.9215, 32.8560,
 now() + interval '3 days', now() + interval '3 days' + interval '3 hours',
 true, true, 100, 150, 'TRY',
 array['akustik', 'canlı müzik', 'Kızılay'], 0.63),

-- ═══════════════════════════════════════════════
--  ANKARA — KÜLTÜR & SANAT
-- ═══════════════════════════════════════════════
('curated',
 'Anadolu Medeniyetleri Müzesi',
 'Dünya''nın en zengin arkeoloji müzelerinden. Hitit, Frig, Urartu eserleri.',
 'culture', 'müze',
 'Anadolu Medeniyetleri Müzesi', 'Gözcü Sok. No:2, Ulus', 'Ankara',
 39.9395, 32.8602,
 null, null,
 true, true, 70, 130, 'TRY',
 array['arkeoloji', 'müze', 'Hitit', 'tarihi'], 0.94),

('curated',
 'Devlet Tiyatroları — Çağdaş Oyun',
 'Büyük Tiyatro''da güncel Türk tiyatrosu.',
 'culture', 'tiyatro',
 'Ankara Devlet Tiyatrosu Büyük Tiyatro', 'Atatürk Bulv., Ulus', 'Ankara',
 39.9340, 32.8598,
 now() + interval '4 days', now() + interval '4 days' + interval '2 hours',
 true, true, 60, 150, 'TRY',
 array['tiyatro', 'devlet', 'Ankara', 'Ulus'], 0.78),

('curated',
 'CerModern Sanat Merkezi Sergisi',
 'Türkiye''nin önde gelen çağdaş sanat mekanında dönem sergisi.',
 'culture', 'sergi',
 'CerModern', 'Altınsoy Cad., Demirtepe', 'Ankara',
 39.9235, 32.8492,
 null, null,
 true, true, 50, 100, 'TRY',
 array['çağdaş sanat', 'sergi', 'Ankara'], 0.76),

-- ═══════════════════════════════════════════════
--  ANKARA — AÇIK HAVA & DOĞA
-- ═══════════════════════════════════════════════
('curated',
 'Eymir Gölü Bisiklet & Yürüyüş',
 'Göl çevresinde 14 km''lik yürüyüş ve bisiklet rotası. Kiralık bisiklet var.',
 'outdoor', 'bisiklet',
 'Eymir Gölü', 'ODTÜ Yerleşkesi, Gölbaşı', 'Ankara',
 39.8640, 32.7773,
 null, null,
 true, false, 0, 40, 'TRY',
 array['bisiklet', 'göl', 'doğa', 'yürüyüş'], 0.88),

('curated',
 'Atatürk Orman Çiftliği Sabah Koşusu',
 'AOÇ''nin geniş yeşil alanında haftalık grup koşusu. Her Pazar 08:00.',
 'outdoor', 'koşu',
 'Atatürk Orman Çiftliği', 'AOÇ Giriş, Yenimahalle', 'Ankara',
 39.9511, 32.8095,
 null, null,
 true, false, 0, 0, 'TRY',
 array['koşu', 'orman', 'sabah', 'ücretsiz'], 0.71),

('curated',
 'Gençlik Parkı Açık Hava Konseri',
 'Yaz boyunca parkta ücretsiz belediye konserleri.',
 'outdoor', 'konser',
 'Gençlik Parkı', 'Ulus, Altındağ', 'Ankara',
 39.9385, 32.8551,
 now() + interval '7 days', now() + interval '7 days' + interval '2 hours',
 true, false, 0, 0, 'TRY',
 array['açık hava', 'konser', 'ücretsiz', 'park'], 0.73),

-- ═══════════════════════════════════════════════
--  ANKARA — YEME-İÇME & ATÖLYE
-- ═══════════════════════════════════════════════
('curated',
 'Ankara Mutfağı Gastronomi Festivali',
 'Ankara kebabı, testi kebabı, beypazarı simidi ve yerel lezzetler festivali.',
 'food', 'festival',
 'ATO Congresium', 'Mevlana Bulv., Yenimahalle', 'Ankara',
 39.9402, 32.8136,
 now() + interval '18 days', now() + interval '20 days',
 false, false, 0, 0, 'TRY',
 array['festival', 'Ankara mutfağı', 'gastronomi'], 0.72),

('curated',
 'Hat Sanatı Atölyesi — Çankaya',
 'Geleneksel Osmanlı hat yazısı başlangıç kursu. Malzemeler dahil.',
 'workshop', 'hat sanatı',
 'Çankaya Kültür Merkezi', 'Çankaya Cad., Çankaya', 'Ankara',
 39.9042, 32.8653,
 now() + interval '12 days', now() + interval '12 days' + interval '3 hours',
 true, true, 200, 350, 'TRY',
 array['hat', 'kaligrafi', 'atölye', 'Osmanlı'], 0.61),

-- ═══════════════════════════════════════════════
--  ANKARA — AİLE
-- ═══════════════════════════════════════════════
('curated',
 'ODTÜ Teknokent Bilim Festivali',
 'Çocuklara yönelik interaktif bilim deneyleri ve robotik gösterileri.',
 'family', 'bilim',
 'ODTÜ Teknokent', 'ODTÜ Kampüsü, Çankaya', 'Ankara',
 39.8913, 32.7793,
 now() + interval '15 days', now() + interval '15 days' + interval '6 hours',
 false, false, 0, 0, 'TRY',
 array['bilim', 'çocuk', 'robot', 'ücretsiz'], 0.77),

('curated',
 'Çocuk Doğa Kampı — Eymir',
 '7-12 yaş için yarım günlük doğa keşif etkinliği. Uzman rehber eşliğinde.',
 'family', 'doğa',
 'Eymir Gölü', 'ODTÜ Yerleşkesi, Gölbaşı', 'Ankara',
 39.8621, 32.7768,
 now() + interval '8 days', now() + interval '8 days' + interval '4 hours',
 true, true, 150, 250, 'TRY',
 array['çocuk', 'doğa', 'kamp', 'aile'], 0.69);
