-- Curated seed: Istanbul (28 events) + Ankara (14 events) = 42 events
-- starts_at values use now() + interval — seed data always stays valid
-- is_recurring = true events have starts_at/ends_at intentionally null

insert into public.events
  (source, title, description, category, subcategory,
   venue_name, address, city, lat, lng,
   starts_at, ends_at, is_recurring, is_ticketed,
   price_min, price_max, currency, tags, popularity_score)
values

-- ═══════════════════════════════════════════════
--  ISTANBUL — MUSIC
-- ═══════════════════════════════════════════════
('curated',
 'Jazz Night — Nardis Jazz Club',
 'International jazz artists performing. Every Thursday evening.',
 'music', 'jazz',
 'Nardis Jazz Club', 'Kuledibi Sok. No:14, Beyoğlu', 'İstanbul',
 41.0282, 28.9740,
 now() + interval '3 days', now() + interval '3 days' + interval '3 hours',
 true, true, 250, 400, 'TRY',
 array['jazz', 'live music', 'Beyoğlu'], 0.82),

('curated',
 'Rock Concert — Küçükçiftlik Park',
 'Open-air concert by Turkish rock bands.',
 'music', 'rock',
 'Küçükçiftlik Park', 'Darülbedai Cad., Şişli', 'İstanbul',
 41.0617, 28.9994,
 now() + interval '8 days', now() + interval '8 days' + interval '4 hours',
 false, true, 350, 550, 'TRY',
 array['rock', 'open air', 'concert'], 0.76),

('curated',
 'Classical Music Concert — Lütfi Kırdar',
 'Istanbul State Symphony Orchestra gala concert.',
 'music', 'classical',
 'Lütfi Kırdar Kongre Merkezi', 'Harbiye, Şişli', 'İstanbul',
 41.0495, 28.9945,
 now() + interval '5 days', now() + interval '5 days' + interval '2 hours 30 minutes',
 false, true, 150, 600, 'TRY',
 array['classical music', 'symphony', 'Harbiye'], 0.71),

('curated',
 'Babylon Live Performance',
 'Alternative and world music artists.',
 'music', 'alternative',
 'Babylon', 'Şehbender Sok. No:3, Asmalımescit', 'İstanbul',
 41.0313, 28.9767,
 now() + interval '2 days', now() + interval '2 days' + interval '3 hours',
 true, true, 200, 350, 'TRY',
 array['live music', 'Beyoğlu', 'nightlife'], 0.79),

('curated',
 'Acoustic Night — Kadıköy Sahne',
 'Underground and indie music artists in acoustic set.',
 'music', 'acoustic',
 'Kadıköy Sahne', 'Moda Cad., Kadıköy', 'İstanbul',
 40.9853, 29.0234,
 now() + interval '4 days', now() + interval '4 days' + interval '3 hours',
 true, true, 100, 200, 'TRY',
 array['acoustic', 'indie', 'Kadıköy'], 0.68),

-- ═══════════════════════════════════════════════
--  ISTANBUL — CULTURE & ARTS
-- ═══════════════════════════════════════════════
('curated',
 'Pera Museum — Permanent Collection',
 'Anatolian Weights and Measures, Kütahya Tiles and Ceramics, Orientalist Painting collections.',
 'culture', 'museum',
 'Pera Müzesi', 'Meşrutiyet Cad. No:65, Tepebaşı', 'İstanbul',
 41.0329, 28.9751,
 null, null,
 true, true, 75, 150, 'TRY',
 array['museum', 'art', 'Beyoğlu'], 0.88),

('curated',
 'Istanbul Modern — Contemporary Art Exhibition',
 'Turkish and international contemporary artworks. New building at Galataport.',
 'culture', 'museum',
 'İstanbul Modern', 'Meclis-i Mebusan Cad., Karaköy', 'İstanbul',
 41.0236, 28.9813,
 null, null,
 true, true, 100, 200, 'TRY',
 array['contemporary art', 'museum', 'Karaköy'], 0.91),

('curated',
 'SALT Galata — Architecture Exhibition',
 'Comprehensive archive and exhibition on Turkish architectural history.',
 'culture', 'exhibition',
 'SALT Galata', 'Bankalar Cad. No:11, Karaköy', 'İstanbul',
 41.0254, 28.9792,
 null, null,
 true, false, 0, 0, 'TRY',
 array['architecture', 'exhibition', 'free', 'Karaköy'], 0.74),

('curated',
 'Sakıp Sabancı Museum — Calligraphy Exhibition',
 'Ottoman calligraphy works and the Sakıp Sabancı collection.',
 'culture', 'museum',
 'Sakıp Sabancı Müzesi', 'Sakıp Sabancı Cad. No:42, Emirgan', 'İstanbul',
 41.0857, 29.0534,
 null, null,
 true, true, 100, 200, 'TRY',
 array['museum', 'calligraphy', 'Emirgan', 'Bosphorus'], 0.85),

('curated',
 'Kadıköy Theatre Festival',
 'Short plays festival by independent theatre groups.',
 'culture', 'theatre',
 'Kadıköy Kültür Merkezi', 'Söğütlüçeşme Cad., Kadıköy', 'İstanbul',
 40.9910, 29.0246,
 now() + interval '10 days', now() + interval '12 days',
 false, true, 50, 150, 'TRY',
 array['theatre', 'festival', 'Kadıköy'], 0.65),

-- ═══════════════════════════════════════════════
--  ISTANBUL — OUTDOORS & NATURE
-- ═══════════════════════════════════════════════
('curated',
 'Maçka Park Morning Yoga',
 'Outdoor yoga in the park every day at 07:30. All levels welcome.',
 'outdoor', 'yoga',
 'Maçka Demokrasi Parkı', 'Maçka, Beşiktaş', 'İstanbul',
 41.0444, 29.0002,
 null, null,
 true, false, 0, 0, 'TRY',
 array['yoga', 'morning', 'park', 'free'], 0.72),

('curated',
 'Emirgan Grove Nature Walk',
 'Guided nature walk on forest paths with Bosphorus views. Weekends.',
 'outdoor', 'nature walk',
 'Emirgan Korusu', 'Emirgan, Sarıyer', 'İstanbul',
 41.0944, 29.0559,
 null, null,
 true, false, 0, 0, 'TRY',
 array['hiking', 'nature', 'Bosphorus', 'free'], 0.78),

('curated',
 'Belgrade Forest Cycling Tour',
 'Forest cycling routes. Bike rental available.',
 'outdoor', 'cycling',
 'Belgrad Ormanı Giriş', 'Bahçeköy, Sarıyer', 'İstanbul',
 41.1611, 28.9713,
 null, null,
 true, false, 0, 50, 'TRY',
 array['cycling', 'forest', 'nature'], 0.81),

('curated',
 'Bosphorus Sunset Boat Tour',
 '2-hour sunset tour passing under the Bosphorus Bridge.',
 'outdoor', 'boat',
 'Beşiktaş İskelesi', 'Beşiktaş Meydanı', 'İstanbul',
 41.0439, 29.0056,
 now() + interval '1 days', now() + interval '1 days' + interval '2 hours',
 true, true, 200, 350, 'TRY',
 array['boat', 'Bosphorus', 'sunset'], 0.89),

('curated',
 'Princes Islands Cycling & Picnic',
 'No cars on Büyükada — explore the island by bike and enjoy a seaside picnic.',
 'outdoor', 'cycling',
 'Büyükada Vapur İskelesi', 'Büyükada, Adalar', 'İstanbul',
 40.8738, 29.1199,
 null, null,
 true, false, 0, 80, 'TRY',
 array['island', 'cycling', 'picnic', 'sea'], 0.86),

-- ═══════════════════════════════════════════════
--  ISTANBUL — FOOD & DRINK
-- ═══════════════════════════════════════════════
('curated',
 'Kadıköy Food Tour',
 'Guided street food tour through the historic market. 10 stops.',
 'food', 'food tour',
 'Kadıköy Çarşısı', 'Mühürdar Cad., Kadıköy', 'İstanbul',
 40.9905, 29.0256,
 null, null,
 true, true, 300, 300, 'TRY',
 array['food', 'tour', 'Kadıköy', 'street food'], 0.83),

('curated',
 'Istanbul Gourmet Festival',
 'The city''s best restaurants and chefs gathered in one place. 3 days.',
 'food', 'festival',
 'Harbiye Cemil Topuzlu Parkı', 'Harbiye, Şişli', 'İstanbul',
 41.0479, 28.9905,
 now() + interval '14 days', now() + interval '16 days',
 false, false, 0, 0, 'TRY',
 array['festival', 'gourmet', 'food', 'open air'], 0.77),

('curated',
 'Karaköy Coffee Festival',
 'Turkey''s specialty coffee producers and baristas.',
 'food', 'festival',
 'SALT Galata Avlusu', 'Bankalar Cad., Karaköy', 'İstanbul',
 41.0252, 28.9789,
 now() + interval '6 days', now() + interval '7 days',
 false, false, 0, 0, 'TRY',
 array['coffee', 'specialty', 'festival', 'Karaköy'], 0.74),

-- ═══════════════════════════════════════════════
--  ISTANBUL — SPORTS
-- ═══════════════════════════════════════════════
('curated',
 'Istanbul Marathon Training Run',
 '10km group run at Fenerbahçe Park every Sunday.',
 'sports', 'running',
 'Fenerbahçe Parkı', 'Bağdat Cad., Kadıköy', 'İstanbul',
 40.9716, 29.0400,
 null, null,
 true, false, 0, 0, 'TRY',
 array['running', 'marathon', 'group', 'free'], 0.69),

('curated',
 'Beach Volleyball — Florya',
 'Beach volleyball every weekend. Open participation.',
 'sports', 'volleyball',
 'Florya Sahili', 'Florya, Bakırköy', 'İstanbul',
 40.9793, 28.7731,
 null, null,
 true, false, 0, 0, 'TRY',
 array['volleyball', 'beach', 'sports', 'open air'], 0.64),

-- ═══════════════════════════════════════════════
--  ISTANBUL — WORKSHOPS & EDUCATION
-- ═══════════════════════════════════════════════
('curated',
 'Ceramics Workshop — Cihangir',
 'Beginner-level pottery throwing and painting. 3-hour session.',
 'workshop', 'ceramics',
 'Cihangir Sanat Atölyesi', 'Akarsu Cad., Cihangir', 'İstanbul',
 41.0340, 28.9808,
 now() + interval '5 days', now() + interval '5 days' + interval '3 hours',
 true, true, 400, 600, 'TRY',
 array['ceramics', 'workshop', 'crafts', 'Cihangir'], 0.71),

('curated',
 'Digital Photography Workshop',
 'Composition and lighting techniques. DSLR or mirrorless required.',
 'workshop', 'photography',
 'Moda Sahil', 'Moda Cad., Kadıköy', 'İstanbul',
 40.9849, 29.0291,
 now() + interval '9 days', now() + interval '9 days' + interval '4 hours',
 false, true, 350, 500, 'TRY',
 array['photography', 'workshop', 'art'], 0.67),

('curated',
 'Turkish Cuisine Cooking Workshop',
 'Traditional Turkish cooking workshop. Ingredients included.',
 'workshop', 'cooking',
 'Cooking Alaturka', 'Akbıyık Cad., Sultanahmet', 'İstanbul',
 41.0047, 28.9760,
 now() + interval '7 days', now() + interval '7 days' + interval '3 hours',
 true, true, 500, 700, 'TRY',
 array['cooking', 'Turkish cuisine', 'workshop'], 0.75),

-- ═══════════════════════════════════════════════
--  ISTANBUL — FAMILY
-- ═══════════════════════════════════════════════
('curated',
 'Children''s Theatre — Fairy Tale Land',
 'Interactive fairy tale play for children aged 4-10.',
 'family', 'theatre',
 'Şişli Kültür Merkezi', 'Halaskargazi Cad., Şişli', 'İstanbul',
 41.0570, 28.9880,
 now() + interval '6 days', now() + interval '6 days' + interval '1 hours 30 minutes',
 true, true, 100, 180, 'TRY',
 array['children', 'theatre', 'family', 'fairy tale'], 0.73),

('curated',
 'Science Centre Weekend Activity',
 'Interactive science experiments and workshops. Ages 6-14.',
 'family', 'education',
 'Koç Müzesi Bilim Merkezi', 'Hasköy Cad., Hasköy', 'İstanbul',
 41.0453, 28.9597,
 null, null,
 true, true, 80, 150, 'TRY',
 array['science', 'children', 'education', 'museum'], 0.80),

('curated',
 'Emirgan Park Picnic Day',
 'Large lawn and children''s playground on the Bosphorus for family picnics.',
 'family', 'picnic',
 'Emirgan Parkı', 'Emirgan, Sarıyer', 'İstanbul',
 41.0918, 29.0549,
 null, null,
 true, false, 0, 0, 'TRY',
 array['picnic', 'park', 'family', 'Bosphorus', 'free'], 0.84),

-- ═══════════════════════════════════════════════
--  ISTANBUL — CULTURE (extra)
-- ═══════════════════════════════════════════════
('curated',
 'Topkapi Palace Guided Tour',
 'Ottoman palace complex including the treasury and harem sections.',
 'culture', 'historic tour',
 'Topkapı Sarayı', 'Sultanahmet, Fatih', 'İstanbul',
 41.0115, 28.9833,
 null, null,
 true, true, 150, 400, 'TRY',
 array['historic', 'museum', 'Ottoman', 'Sultanahmet'], 0.93),

('curated',
 'Street Art Tour — Karaköy & Tophane',
 'Discover the graffiti and street art of Karaköy.',
 'culture', 'tour',
 'Karaköy Meydanı', 'Karaköy, Beyoğlu', 'İstanbul',
 41.0232, 28.9748,
 null, null,
 true, true, 150, 200, 'TRY',
 array['street art', 'tour', 'Karaköy', 'art'], 0.66),

-- ═══════════════════════════════════════════════
--  ANKARA — MUSIC
-- ═══════════════════════════════════════════════
('curated',
 'Presidential Symphony Orchestra Concert',
 'CSO monthly subscription concert. International soloists.',
 'music', 'classical',
 'CSO Ada Ankara', 'Çukurambar Mah., Çankaya', 'Ankara',
 39.9051, 32.8229,
 now() + interval '11 days', now() + interval '11 days' + interval '2 hours 30 minutes',
 true, true, 100, 500, 'TRY',
 array['symphony', 'classical music', 'CSO', 'Ankara'], 0.87),

('curated',
 'Ankara Jazz Festival',
 'National and international jazz artists in outdoor and indoor venues.',
 'music', 'jazz',
 'Kızılay Meydanı & Çeşitli Mekanlar', 'Çankaya, Ankara', 'Ankara',
 39.9199, 32.8543,
 now() + interval '20 days', now() + interval '23 days',
 false, false, 0, 200, 'TRY',
 array['jazz', 'festival', 'Ankara', 'open air'], 0.79),

('curated',
 'Acoustic Night — Keyifli Mekan',
 'Weekly acoustic performance at Kızılay''s popular bar stage.',
 'music', 'acoustic',
 'Keyifli Mekan', 'Konur Sok., Kızılay', 'Ankara',
 39.9215, 32.8560,
 now() + interval '3 days', now() + interval '3 days' + interval '3 hours',
 true, true, 100, 150, 'TRY',
 array['acoustic', 'live music', 'Kızılay'], 0.63),

-- ═══════════════════════════════════════════════
--  ANKARA — CULTURE & ARTS
-- ═══════════════════════════════════════════════
('curated',
 'Museum of Anatolian Civilisations',
 'One of the world''s richest archaeology museums. Hittite, Phrygian, Urartian artefacts.',
 'culture', 'museum',
 'Anadolu Medeniyetleri Müzesi', 'Gözcü Sok. No:2, Ulus', 'Ankara',
 39.9395, 32.8602,
 null, null,
 true, true, 70, 130, 'TRY',
 array['archaeology', 'museum', 'Hittite', 'historic'], 0.94),

('curated',
 'State Theatres — Contemporary Play',
 'Contemporary Turkish theatre at the Grand Theatre.',
 'culture', 'theatre',
 'Ankara Devlet Tiyatrosu Büyük Tiyatro', 'Atatürk Bulv., Ulus', 'Ankara',
 39.9340, 32.8598,
 now() + interval '4 days', now() + interval '4 days' + interval '2 hours',
 true, true, 60, 150, 'TRY',
 array['theatre', 'state', 'Ankara', 'Ulus'], 0.78),

('curated',
 'CerModern Art Centre Exhibition',
 'Seasonal exhibition at Turkey''s leading contemporary art venue.',
 'culture', 'exhibition',
 'CerModern', 'Altınsoy Cad., Demirtepe', 'Ankara',
 39.9235, 32.8492,
 null, null,
 true, true, 50, 100, 'TRY',
 array['contemporary art', 'exhibition', 'Ankara'], 0.76),

-- ═══════════════════════════════════════════════
--  ANKARA — OUTDOORS & NATURE
-- ═══════════════════════════════════════════════
('curated',
 'Eymir Lake Cycling & Hiking',
 '14 km cycling and hiking route around the lake. Bike rental available.',
 'outdoor', 'cycling',
 'Eymir Gölü', 'ODTÜ Yerleşkesi, Gölbaşı', 'Ankara',
 39.8640, 32.7773,
 null, null,
 true, false, 0, 40, 'TRY',
 array['cycling', 'lake', 'nature', 'hiking'], 0.88),

('curated',
 'Atatürk Forest Farm Morning Run',
 'Weekly group run in the vast green space of AOÇ. Every Sunday at 08:00.',
 'outdoor', 'running',
 'Atatürk Orman Çiftliği', 'AOÇ Giriş, Yenimahalle', 'Ankara',
 39.9511, 32.8095,
 null, null,
 true, false, 0, 0, 'TRY',
 array['running', 'forest', 'morning', 'free'], 0.71),

('curated',
 'Gençlik Park Open-Air Concert',
 'Free municipal concerts in the park throughout summer.',
 'outdoor', 'concert',
 'Gençlik Parkı', 'Ulus, Altındağ', 'Ankara',
 39.9385, 32.8551,
 now() + interval '7 days', now() + interval '7 days' + interval '2 hours',
 true, false, 0, 0, 'TRY',
 array['open air', 'concert', 'free', 'park'], 0.73),

-- ═══════════════════════════════════════════════
--  ANKARA — FOOD & WORKSHOPS
-- ═══════════════════════════════════════════════
('curated',
 'Ankara Gastronomy Festival',
 'Ankara kebab, testi kebab, Beypazarı simit and local flavours festival.',
 'food', 'festival',
 'ATO Congresium', 'Mevlana Bulv., Yenimahalle', 'Ankara',
 39.9402, 32.8136,
 now() + interval '18 days', now() + interval '20 days',
 false, false, 0, 0, 'TRY',
 array['festival', 'Ankara cuisine', 'gastronomy'], 0.72),

('curated',
 'Calligraphy Workshop — Çankaya',
 'Beginner course in traditional Ottoman calligraphy. Materials included.',
 'workshop', 'calligraphy',
 'Çankaya Kültür Merkezi', 'Çankaya Cad., Çankaya', 'Ankara',
 39.9042, 32.8653,
 now() + interval '12 days', now() + interval '12 days' + interval '3 hours',
 true, true, 200, 350, 'TRY',
 array['calligraphy', 'art', 'workshop', 'Ottoman'], 0.61),

-- ═══════════════════════════════════════════════
--  ANKARA — FAMILY
-- ═══════════════════════════════════════════════
('curated',
 'METU Technopark Science Festival',
 'Interactive science experiments and robotics demonstrations for children.',
 'family', 'science',
 'ODTÜ Teknokent', 'ODTÜ Kampüsü, Çankaya', 'Ankara',
 39.8913, 32.7793,
 now() + interval '15 days', now() + interval '15 days' + interval '6 hours',
 false, false, 0, 0, 'TRY',
 array['science', 'children', 'robotics', 'free'], 0.77),

('curated',
 'Children''s Nature Camp — Eymir',
 'Half-day nature discovery activity for ages 7-12. Expert guide included.',
 'family', 'nature',
 'Eymir Gölü', 'ODTÜ Yerleşkesi, Gölbaşı', 'Ankara',
 39.8621, 32.7768,
 now() + interval '8 days', now() + interval '8 days' + interval '4 hours',
 true, true, 150, 250, 'TRY',
 array['children', 'nature', 'camp', 'family'], 0.69);
